# Generated by Django 2.0.3 on 2019-06-23 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='提示时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
            ],
            options={
                'verbose_name': '提示信息',
                'verbose_name_plural': '提示信息',
                'ordering': ['-create_date'],
            },
        ),
        migrations.RemoveField(
            model_name='aboutcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='aboutcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='aboutcomment',
            name='rep_to',
        ),
        migrations.RemoveField(
            model_name='messagecomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='messagecomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='messagecomment',
            name='rep_to',
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articlecomment_related', to=settings.AUTH_USER_MODEL, verbose_name='评论人'),
        ),
        migrations.DeleteModel(
            name='AboutComment',
        ),
        migrations.DeleteModel(
            name='CommentUser',
        ),
        migrations.DeleteModel(
            name='MessageComment',
        ),
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_comment', to='comment.ArticleComment', verbose_name='所属评论'),
        ),
        migrations.AddField(
            model_name='notification',
            name='create_p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_create', to=settings.AUTH_USER_MODEL, verbose_name='提示创建者'),
        ),
        migrations.AddField(
            model_name='notification',
            name='get_p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_get', to=settings.AUTH_USER_MODEL, verbose_name='提示接收者'),
        ),
    ]
