# Generated by Django 2.0.3 on 2019-06-25 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20190625_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='author',
            field=models.ForeignKey(default='2', null='False', on_delete=django.db.models.deletion.CASCADE, related_name='articlecomment_related', to=settings.AUTH_USER_MODEL, verbose_name='评论人'),
            
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='belong',
            field=models.ForeignKey(default='4', null='False', on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='blog.Article', verbose_name='所属文章'),
        ),
    ]
