# Generated by Django 2.0.3 on 2019-06-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toollink',
            name='img',
            field=models.ImageField(default='/static/images/summary.jpg', null=True, upload_to='media'),
        ),
    ]
