# Generated by Django 2.0.3 on 2019-06-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_toollink_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toollink',
            name='img',
            field=models.ImageField(blank=True, default='/static/images/summary.jpg', null=True, upload_to='media'),
        ),
    ]
