# Generated by Django 2.0.3 on 2019-11-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_auto_20190629_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toollink',
            options={'ordering': ['order_num', 'id'], 'verbose_name': '工具', 'verbose_name_plural': '工具'},
        ),
        migrations.AlterField(
            model_name='toollink',
            name='img',
            field=models.ImageField(blank=True, default='/static/images/summary.jpg', null=True, upload_to=' media'),
        ),
    ]
