# Generated by Django 2.0.3 on 2019-11-14 05:14

import apps.tool.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_auto_20191113_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toollink',
            name='img',
            field=models.ImageField(blank=True, default='/static/images/summary.jpg', null=True, storage=apps.tool.models.ImageStorage(), upload_to='media/tool'),
        ),
    ]
