# Generated by Django 2.0.3 on 2019-06-29 14:54

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='avatar/default.png', null=True, upload_to='avatar/%Y/%m/%d', verbose_name='头像'),
        ),
    ]
