# Generated by Django 2.0.3 on 2019-07-02 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190702_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ['id'], 'verbose_name': '通讯录', 'verbose_name_plural': '通讯录'},
        ),
    ]
