# Generated by Django 2.0.3 on 2019-06-29 15:00

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190629_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='avatar/default.png', upload_to='avatar/%Y/%m/%d', verbose_name='头像'),
        ),
    ]
