# Generated by Django 2.0.3 on 2020-01-06 01:57

import apps.blog.models
from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='文章标题')),
                ('summary', mdeditor.fields.MDTextField(default='文章摘要等同于网页description内容，请务必填写...', max_length=230, verbose_name='文章摘要')),
                ('body', mdeditor.fields.MDTextField(verbose_name='文章内容')),
                ('create_date', models.DateTimeField(verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('views', models.IntegerField(default=0, verbose_name='阅览量')),
                ('img', models.ImageField(default='artile/default.png', storage=apps.blog.models.ImageStorage(), upload_to='article/%Y%m%d')),
                ('slug', models.SlugField(editable=False)),
                ('is_top', models.BooleanField(default=False, verbose_name='是否首页展示')),
                ('is_addtimeline', models.BooleanField(default=False, verbose_name='是否添加时间线')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='文章分类')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(default='Stray_Camel的个人技术博客，django_blog，django2.0+python3技术搭建。', help_text='用来作为SEO中description,长度参考SEO标准', max_length=240, verbose_name='描述')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='网站名称')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='网站描述')),
                ('link', models.URLField(help_text='请填写http或https开头的完整形式地址', verbose_name='友链地址')),
                ('logo', models.URLField(blank=True, help_text='请填写http或https开头的完整形式地址', verbose_name='网站LOGO')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否首页展示')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'ordering': ['create_date'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='文章关键词')),
            ],
            options={
                'verbose_name': '关键词',
                'verbose_name_plural': '关键词',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('L', '左边'), ('R', '右边')], default='L', max_length=1, verbose_name='位置')),
                ('icon', models.CharField(default='fa fa-pencil', max_length=50, verbose_name='图标')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('update_date', models.DateTimeField(verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='主要内容')),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
            ],
            options={
                'verbose_name': '博客升级时间线',
                'verbose_name_plural': '博客升级时间线',
                'ordering': ['-update_date'],
            },
        ),
    ]
