# Generated by Django 2.0.3 on 2019-06-28 08:34

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190628_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=mdeditor.fields.MDTextField(verbose_name='文章内容'),
        ),
    ]
