# Generated by Django 2.0.3 on 2019-06-25 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190625_1455'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default='2', null='False', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default='2', null='False', on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='文章分类'),
        ),
    ]
