# Generated by Django 2.0.3 on 2019-06-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190628_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(default='/static/images/summary.jpg', null=True, upload_to='media'),
        ),
    ]
