# Generated by Django 2.0.3 on 2019-06-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190623_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='loves',
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
