# Generated by Django 2.0.3 on 2019-06-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190623_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '大分类', 'verbose_name_plural': '大分类'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='categoty',
        ),
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.TextField(default='娃哈哈店长,静觅,网络,IT,技术,博客,Python', help_text='用来作为SEO中keywords,长度参考SEO标准', max_length=240, verbose_name='关键字'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, verbose_name='文章大分类'),
        ),
    ]
