# Generated by Django 2.0.3 on 2019-11-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191113_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='img',
        ),
        migrations.AddField(
            model_name='article',
            name='img_source',
            field=models.ImageField(default='1.png', upload_to='media/article'),
        ),
    ]
