# Generated by Django 2.0.3 on 2019-06-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190624_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default='/static/images/summary.jpg', upload_to='media'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='img',
            field=models.ImageField(default='/static/images/summary.jpg', upload_to='media'),
        ),
    ]
