# Generated by Django 2.0.3 on 2019-11-13 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191113_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='img_source',
            new_name='img',
        ),
    ]
