# Generated by Django 2.0.3 on 2019-11-14 05:14

import apps.blog.models
from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191113_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('L', '左边'), ('R', '右边')], default='L', max_length=1, verbose_name='位置')),
                ('icon', models.CharField(default='fa fa-pencil', max_length=50, verbose_name='图标')),
                ('icon_color', models.CharField(choices=[('primary', '基本-蓝色'), ('success', '成功-绿色'), ('info', '信息-天蓝色'), ('warning', '警告-橙色'), ('danger', '危险-红色')], default='info', max_length=20, verbose_name='图标颜色')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('update_date', models.DateTimeField(verbose_name='更新时间')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('views', models.IntegerField(default=0, verbose_name='阅览量')),
                ('content', models.TextField(verbose_name='主要内容')),
                ('body', mdeditor.fields.MDTextField(verbose_name='文章内容')),
                ('img', models.ImageField(default='1.png', storage=apps.blog.models.ImageStorage(), upload_to='media/article')),
            ],
            options={
                'verbose_name': '博客升级时间线',
                'verbose_name_plural': '博客升级时间线',
                'ordering': ['update_date'],
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(default='1.png', storage=apps.blog.models.ImageStorage(), upload_to='media/article'),
        ),
    ]
