# Generated by Django 2.0.3 on 2019-11-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191114_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
    ]
