# Generated by Django 2.0.3 on 2019-11-14 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191114_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='body',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='img',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='views',
        ),
    ]
