# Generated by Django 2.0.3 on 2019-11-14 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20191114_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='icon_color',
        ),
    ]
