# Generated by Django 2.0.3 on 2019-11-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_timeline_icon_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_addtimeline',
            field=models.BooleanField(default=False, verbose_name='是否更新时间线'),
        ),
    ]
