# Generated by Django 2.0.3 on 2019-11-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20191114_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
    ]
