# Generated by Django 2.0.3 on 2019-12-23 07:36

import apps.blog.models
from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_timeline_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ['-update_date'], 'verbose_name': '博客升级时间线', 'verbose_name_plural': '博客升级时间线'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='img_link',
        ),
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(default='artile/default.png', storage=apps.blog.models.ImageStorage(), upload_to='article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=mdeditor.fields.MDTextField(default='文章摘要等同于网页description内容，请务必填写...', max_length=230, verbose_name='文章摘要'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='update_date',
            field=models.DateTimeField(verbose_name='更新时间'),
        ),
    ]
